// This file is @generated by prost-build.
/// Lane metrics with cluster assignment
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LaneMetrics {
    #[prost(string, tag = "1")]
    pub origin_zip: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub dest_zip: ::prost::alloc::string::String,
    /// Formatted route (e.g., "DFW→TUS")
    #[prost(string, tag = "3")]
    pub route: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub volume: i64,
    #[prost(double, tag = "5")]
    pub avg_delay: f64,
    #[prost(double, tag = "6")]
    pub transit_variance: f64,
    #[prost(double, tag = "7")]
    pub early_rate: f64,
    #[prost(double, tag = "8")]
    pub on_time_rate: f64,
    #[prost(double, tag = "9")]
    pub late_rate: f64,
    #[prost(uint32, tag = "10")]
    pub cluster_id: u32,
    #[prost(string, tag = "11")]
    pub cluster_name: ::prost::alloc::string::String,
}
/// Cluster summary
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Cluster {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub lane_count: i64,
    #[prost(int64, tag = "5")]
    pub total_volume: i64,
    #[prost(double, tag = "6")]
    pub avg_delay: f64,
    #[prost(double, tag = "7")]
    pub avg_late_rate: f64,
}
/// Cluster playbook with recommendations
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Playbook {
    #[prost(uint32, tag = "1")]
    pub cluster_id: u32,
    #[prost(string, tag = "2")]
    pub cluster_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub actions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Friction zone (problem destination)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FrictionZone {
    #[prost(string, tag = "1")]
    pub dest_zip: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub location: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    pub friction_score: f64,
    #[prost(double, tag = "4")]
    pub late_rate: f64,
    #[prost(double, tag = "5")]
    pub transit_variance: f64,
    #[prost(int64, tag = "6")]
    pub volume: i64,
    #[prost(int64, tag = "7")]
    pub lane_count: i64,
}
/// Terminal/DC performance
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TerminalPerformance {
    #[prost(string, tag = "1")]
    pub origin_zip: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub terminal: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    pub performance_score: f64,
    #[prost(double, tag = "4")]
    pub on_time_rate: f64,
    #[prost(double, tag = "5")]
    pub late_rate: f64,
    #[prost(double, tag = "6")]
    pub early_rate: f64,
    #[prost(int64, tag = "7")]
    pub volume: i64,
    #[prost(int64, tag = "8")]
    pub lane_count: i64,
}
/// Regional cluster breakdown
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClusterBreakdown {
    #[prost(string, tag = "1")]
    pub cluster: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub lane_count: i64,
    #[prost(int64, tag = "3")]
    pub volume: i64,
}
/// Regional performance summary
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RegionalSummary {
    #[prost(int64, tag = "1")]
    pub total_lanes: i64,
    #[prost(int64, tag = "2")]
    pub total_volume: i64,
    #[prost(double, tag = "3")]
    pub avg_late_rate: f64,
    #[prost(double, tag = "4")]
    pub avg_early_rate: f64,
    #[prost(double, tag = "5")]
    pub avg_delay: f64,
}
/// Early delivery destination
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EarlyDestination {
    #[prost(string, tag = "1")]
    pub dest_zip: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub location: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    pub early_rate: f64,
    #[prost(double, tag = "4")]
    pub avg_days_early: f64,
    #[prost(int64, tag = "5")]
    pub early_shipments: i64,
    #[prost(int64, tag = "6")]
    pub volume: i64,
}
/// Database statistics
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Stats {
    #[prost(int64, tag = "1")]
    pub total_shipments: i64,
    #[prost(int64, tag = "2")]
    pub total_lanes: i64,
    #[prost(int64, tag = "3")]
    pub total_carriers: i64,
    #[prost(int64, tag = "4")]
    pub total_locations: i64,
    #[prost(double, tag = "5")]
    pub overall_on_time_rate: f64,
    #[prost(double, tag = "6")]
    pub overall_late_rate: f64,
    #[prost(double, tag = "7")]
    pub overall_early_rate: f64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Empty {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetLanesRequest {
    /// Filter by cluster
    #[prost(uint32, optional, tag = "1")]
    pub cluster_id: ::core::option::Option<u32>,
    /// Max results
    #[prost(int32, optional, tag = "2")]
    pub limit: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLanesResponse {
    #[prost(message, repeated, tag = "1")]
    pub lanes: ::prost::alloc::vec::Vec<LaneMetrics>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLaneRequest {
    #[prost(string, tag = "1")]
    pub origin: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub dest: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLaneResponse {
    #[prost(message, optional, tag = "1")]
    pub lane: ::core::option::Option<LaneMetrics>,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetClustersRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetClustersResponse {
    #[prost(message, repeated, tag = "1")]
    pub clusters: ::prost::alloc::vec::Vec<Cluster>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetClusterLanesRequest {
    #[prost(uint32, tag = "1")]
    pub cluster_id: u32,
    #[prost(int32, tag = "2")]
    pub limit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetClusterLanesResponse {
    #[prost(message, repeated, tag = "1")]
    pub lanes: ::prost::alloc::vec::Vec<LaneMetrics>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetPlaybookRequest {
    #[prost(uint32, tag = "1")]
    pub cluster_id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPlaybookResponse {
    #[prost(message, optional, tag = "1")]
    pub playbook: ::core::option::Option<Playbook>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRegionRequest {
    #[prost(string, tag = "1")]
    pub zip3: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRegionResponse {
    #[prost(string, tag = "1")]
    pub region: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub summary: ::core::option::Option<RegionalSummary>,
    #[prost(message, repeated, tag = "3")]
    pub cluster_breakdown: ::prost::alloc::vec::Vec<ClusterBreakdown>,
    #[prost(message, repeated, tag = "4")]
    pub highest_friction_lanes: ::prost::alloc::vec::Vec<LaneMetrics>,
    #[prost(string, tag = "5")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetFrictionZonesRequest {
    #[prost(int32, tag = "1")]
    pub limit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFrictionZonesResponse {
    #[prost(message, repeated, tag = "1")]
    pub zones: ::prost::alloc::vec::Vec<FrictionZone>,
    #[prost(string, repeated, tag = "2")]
    pub recommendations: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetTerminalsRequest {
    #[prost(int32, tag = "1")]
    pub limit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTerminalsResponse {
    #[prost(int64, tag = "1")]
    pub total_terminals: i64,
    #[prost(int64, tag = "2")]
    pub total_volume: i64,
    #[prost(double, tag = "3")]
    pub average_score: f64,
    #[prost(message, repeated, tag = "4")]
    pub top_performers: ::prost::alloc::vec::Vec<TerminalPerformance>,
    #[prost(message, repeated, tag = "5")]
    pub needs_improvement: ::prost::alloc::vec::Vec<TerminalPerformance>,
    #[prost(string, repeated, tag = "6")]
    pub recommendations: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetEarlyAnalysisRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEarlyAnalysisResponse {
    #[prost(int64, tag = "1")]
    pub total_shipments: i64,
    #[prost(int64, tag = "2")]
    pub early_shipments: i64,
    #[prost(double, tag = "3")]
    pub early_rate: f64,
    #[prost(message, repeated, tag = "4")]
    pub top_destinations: ::prost::alloc::vec::Vec<EarlyDestination>,
    #[prost(string, repeated, tag = "5")]
    pub recommendations: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FindSimilarRequest {
    #[prost(string, tag = "1")]
    pub pattern: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub limit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FindSimilarResponse {
    #[prost(message, optional, tag = "1")]
    pub target_lane: ::core::option::Option<LaneMetrics>,
    #[prost(message, repeated, tag = "2")]
    pub similar_lanes: ::prost::alloc::vec::Vec<LaneMetrics>,
    #[prost(string, tag = "3")]
    pub shared_playbook: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetStatsRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetStatsResponse {
    #[prost(message, optional, tag = "1")]
    pub stats: ::core::option::Option<Stats>,
}
/// Generated client implementations.
pub mod analytics_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct AnalyticsServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AnalyticsServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AnalyticsServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AnalyticsServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AnalyticsServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Lane operations
        pub async fn get_lanes(
            &mut self,
            request: impl tonic::IntoRequest<super::GetLanesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetLanesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lastmile.v1.AnalyticsService/GetLanes",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lastmile.v1.AnalyticsService", "GetLanes"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_lane(
            &mut self,
            request: impl tonic::IntoRequest<super::GetLaneRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetLaneResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lastmile.v1.AnalyticsService/GetLane",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lastmile.v1.AnalyticsService", "GetLane"));
            self.inner.unary(req, path, codec).await
        }
        /// Cluster operations
        pub async fn get_clusters(
            &mut self,
            request: impl tonic::IntoRequest<super::GetClustersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetClustersResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lastmile.v1.AnalyticsService/GetClusters",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lastmile.v1.AnalyticsService", "GetClusters"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_cluster_lanes(
            &mut self,
            request: impl tonic::IntoRequest<super::GetClusterLanesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetClusterLanesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lastmile.v1.AnalyticsService/GetClusterLanes",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("lastmile.v1.AnalyticsService", "GetClusterLanes"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_playbook(
            &mut self,
            request: impl tonic::IntoRequest<super::GetPlaybookRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPlaybookResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lastmile.v1.AnalyticsService/GetPlaybook",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lastmile.v1.AnalyticsService", "GetPlaybook"));
            self.inner.unary(req, path, codec).await
        }
        /// Regional analysis
        pub async fn get_region(
            &mut self,
            request: impl tonic::IntoRequest<super::GetRegionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetRegionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lastmile.v1.AnalyticsService/GetRegion",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lastmile.v1.AnalyticsService", "GetRegion"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_friction_zones(
            &mut self,
            request: impl tonic::IntoRequest<super::GetFrictionZonesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetFrictionZonesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lastmile.v1.AnalyticsService/GetFrictionZones",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("lastmile.v1.AnalyticsService", "GetFrictionZones"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_terminals(
            &mut self,
            request: impl tonic::IntoRequest<super::GetTerminalsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetTerminalsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lastmile.v1.AnalyticsService/GetTerminals",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lastmile.v1.AnalyticsService", "GetTerminals"));
            self.inner.unary(req, path, codec).await
        }
        /// Delivery analysis
        pub async fn get_early_analysis(
            &mut self,
            request: impl tonic::IntoRequest<super::GetEarlyAnalysisRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetEarlyAnalysisResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lastmile.v1.AnalyticsService/GetEarlyAnalysis",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("lastmile.v1.AnalyticsService", "GetEarlyAnalysis"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn find_similar(
            &mut self,
            request: impl tonic::IntoRequest<super::FindSimilarRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FindSimilarResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lastmile.v1.AnalyticsService/FindSimilar",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lastmile.v1.AnalyticsService", "FindSimilar"));
            self.inner.unary(req, path, codec).await
        }
        /// Statistics
        pub async fn get_stats(
            &mut self,
            request: impl tonic::IntoRequest<super::GetStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStatsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lastmile.v1.AnalyticsService/GetStats",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lastmile.v1.AnalyticsService", "GetStats"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod analytics_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AnalyticsServiceServer.
    #[async_trait]
    pub trait AnalyticsService: std::marker::Send + std::marker::Sync + 'static {
        /// Lane operations
        async fn get_lanes(
            &self,
            request: tonic::Request<super::GetLanesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetLanesResponse>,
            tonic::Status,
        >;
        async fn get_lane(
            &self,
            request: tonic::Request<super::GetLaneRequest>,
        ) -> std::result::Result<tonic::Response<super::GetLaneResponse>, tonic::Status>;
        /// Cluster operations
        async fn get_clusters(
            &self,
            request: tonic::Request<super::GetClustersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetClustersResponse>,
            tonic::Status,
        >;
        async fn get_cluster_lanes(
            &self,
            request: tonic::Request<super::GetClusterLanesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetClusterLanesResponse>,
            tonic::Status,
        >;
        async fn get_playbook(
            &self,
            request: tonic::Request<super::GetPlaybookRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPlaybookResponse>,
            tonic::Status,
        >;
        /// Regional analysis
        async fn get_region(
            &self,
            request: tonic::Request<super::GetRegionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetRegionResponse>,
            tonic::Status,
        >;
        async fn get_friction_zones(
            &self,
            request: tonic::Request<super::GetFrictionZonesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetFrictionZonesResponse>,
            tonic::Status,
        >;
        async fn get_terminals(
            &self,
            request: tonic::Request<super::GetTerminalsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetTerminalsResponse>,
            tonic::Status,
        >;
        /// Delivery analysis
        async fn get_early_analysis(
            &self,
            request: tonic::Request<super::GetEarlyAnalysisRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetEarlyAnalysisResponse>,
            tonic::Status,
        >;
        async fn find_similar(
            &self,
            request: tonic::Request<super::FindSimilarRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FindSimilarResponse>,
            tonic::Status,
        >;
        /// Statistics
        async fn get_stats(
            &self,
            request: tonic::Request<super::GetStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStatsResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct AnalyticsServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AnalyticsServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AnalyticsServiceServer<T>
    where
        T: AnalyticsService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/lastmile.v1.AnalyticsService/GetLanes" => {
                    #[allow(non_camel_case_types)]
                    struct GetLanesSvc<T: AnalyticsService>(pub Arc<T>);
                    impl<
                        T: AnalyticsService,
                    > tonic::server::UnaryService<super::GetLanesRequest>
                    for GetLanesSvc<T> {
                        type Response = super::GetLanesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetLanesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AnalyticsService>::get_lanes(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetLanesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lastmile.v1.AnalyticsService/GetLane" => {
                    #[allow(non_camel_case_types)]
                    struct GetLaneSvc<T: AnalyticsService>(pub Arc<T>);
                    impl<
                        T: AnalyticsService,
                    > tonic::server::UnaryService<super::GetLaneRequest>
                    for GetLaneSvc<T> {
                        type Response = super::GetLaneResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetLaneRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AnalyticsService>::get_lane(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetLaneSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lastmile.v1.AnalyticsService/GetClusters" => {
                    #[allow(non_camel_case_types)]
                    struct GetClustersSvc<T: AnalyticsService>(pub Arc<T>);
                    impl<
                        T: AnalyticsService,
                    > tonic::server::UnaryService<super::GetClustersRequest>
                    for GetClustersSvc<T> {
                        type Response = super::GetClustersResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetClustersRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AnalyticsService>::get_clusters(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetClustersSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lastmile.v1.AnalyticsService/GetClusterLanes" => {
                    #[allow(non_camel_case_types)]
                    struct GetClusterLanesSvc<T: AnalyticsService>(pub Arc<T>);
                    impl<
                        T: AnalyticsService,
                    > tonic::server::UnaryService<super::GetClusterLanesRequest>
                    for GetClusterLanesSvc<T> {
                        type Response = super::GetClusterLanesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetClusterLanesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AnalyticsService>::get_cluster_lanes(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetClusterLanesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lastmile.v1.AnalyticsService/GetPlaybook" => {
                    #[allow(non_camel_case_types)]
                    struct GetPlaybookSvc<T: AnalyticsService>(pub Arc<T>);
                    impl<
                        T: AnalyticsService,
                    > tonic::server::UnaryService<super::GetPlaybookRequest>
                    for GetPlaybookSvc<T> {
                        type Response = super::GetPlaybookResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetPlaybookRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AnalyticsService>::get_playbook(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetPlaybookSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lastmile.v1.AnalyticsService/GetRegion" => {
                    #[allow(non_camel_case_types)]
                    struct GetRegionSvc<T: AnalyticsService>(pub Arc<T>);
                    impl<
                        T: AnalyticsService,
                    > tonic::server::UnaryService<super::GetRegionRequest>
                    for GetRegionSvc<T> {
                        type Response = super::GetRegionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetRegionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AnalyticsService>::get_region(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetRegionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lastmile.v1.AnalyticsService/GetFrictionZones" => {
                    #[allow(non_camel_case_types)]
                    struct GetFrictionZonesSvc<T: AnalyticsService>(pub Arc<T>);
                    impl<
                        T: AnalyticsService,
                    > tonic::server::UnaryService<super::GetFrictionZonesRequest>
                    for GetFrictionZonesSvc<T> {
                        type Response = super::GetFrictionZonesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetFrictionZonesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AnalyticsService>::get_friction_zones(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetFrictionZonesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lastmile.v1.AnalyticsService/GetTerminals" => {
                    #[allow(non_camel_case_types)]
                    struct GetTerminalsSvc<T: AnalyticsService>(pub Arc<T>);
                    impl<
                        T: AnalyticsService,
                    > tonic::server::UnaryService<super::GetTerminalsRequest>
                    for GetTerminalsSvc<T> {
                        type Response = super::GetTerminalsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetTerminalsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AnalyticsService>::get_terminals(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetTerminalsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lastmile.v1.AnalyticsService/GetEarlyAnalysis" => {
                    #[allow(non_camel_case_types)]
                    struct GetEarlyAnalysisSvc<T: AnalyticsService>(pub Arc<T>);
                    impl<
                        T: AnalyticsService,
                    > tonic::server::UnaryService<super::GetEarlyAnalysisRequest>
                    for GetEarlyAnalysisSvc<T> {
                        type Response = super::GetEarlyAnalysisResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetEarlyAnalysisRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AnalyticsService>::get_early_analysis(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetEarlyAnalysisSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lastmile.v1.AnalyticsService/FindSimilar" => {
                    #[allow(non_camel_case_types)]
                    struct FindSimilarSvc<T: AnalyticsService>(pub Arc<T>);
                    impl<
                        T: AnalyticsService,
                    > tonic::server::UnaryService<super::FindSimilarRequest>
                    for FindSimilarSvc<T> {
                        type Response = super::FindSimilarResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FindSimilarRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AnalyticsService>::find_similar(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FindSimilarSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lastmile.v1.AnalyticsService/GetStats" => {
                    #[allow(non_camel_case_types)]
                    struct GetStatsSvc<T: AnalyticsService>(pub Arc<T>);
                    impl<
                        T: AnalyticsService,
                    > tonic::server::UnaryService<super::GetStatsRequest>
                    for GetStatsSvc<T> {
                        type Response = super::GetStatsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetStatsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AnalyticsService>::get_stats(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetStatsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AnalyticsServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "lastmile.v1.AnalyticsService";
    impl<T> tonic::server::NamedService for AnalyticsServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
